export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/register'
export const SHOP_ROUTE = '/'
export const CART_ROUTE = '/cart'
export const LOGOUT_ROUTE = '/logout'